apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students-app
  template:
    metadata:
      labels:
        app: students-app
    spec:
      containers:
      - name: students-app-container
        image: malek50/students-app:latest 
        ports:
        - containerPort: 8080
        env: # <--- AJOUTEZ LE BLOC ENV POUR LA CONNEXION DB
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/db_example?useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root" # (OU VOTRE UTILISATEUR MYSQL)
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password" # (OU VOTRE MOT DE PASSE MYSQL)
---
# k8s/service.yaml - Service pour exposer l'application
apiVersion: v1
kind: Service
metadata:
  name: students-app-service
spec:
  type: LoadBalancer 
  selector:
    app: students-app
  ports:
  - port: 80
    targetPort: 8080